-- MySQL Script generated by MySQL Workbench
-- Sun Oct 16 16:51:50 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ametista
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ametista` ;

-- -----------------------------------------------------
-- Schema ametista
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ametista` DEFAULT CHARACTER SET utf8 ;
USE `ametista` ;

-- -----------------------------------------------------
-- Table `ametista`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Users` (
  `cpf` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NULL,
  `password` VARCHAR(100) NOT NULL,
  `status` VARCHAR(100) NULL,
  `user_level` INT NULL,
  `user_image` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`LogStatusUsers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`LogStatusUsers` (
  `idLogStatus` INT NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idLogStatus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Clients` (
  `cpf` VARCHAR(100) NOT NULL,
  `name` VARCHAR(100) NULL,
  `email` VARCHAR(100) NULL,
  `phone` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `language` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Subjects` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `category` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Requests` (
  `id` CHAR(10) NOT NULL,
  `Client_cpf` VARCHAR(100) NOT NULL,
  `category` VARCHAR(100) NULL,
  `endedAt` TIMESTAMP NULL,
  `description` VARCHAR(100) NULL,
  `deadline` TIMESTAMP NULL,
  `priority` INT NULL,
  `comment` VARCHAR(100) NULL,
  `status` VARCHAR(100) NULL,
  `idLanguage` INT NOT NULL,
  `idSubject` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`, `Client_cpf`),
  INDEX `fk_Request_Client1_idx` (`Client_cpf` ASC),
  INDEX `fk_Request_Language1_idx` (`idLanguage` ASC),
  INDEX `fk_Request_Subject1_idx` (`idSubject` ASC),
  CONSTRAINT `fk_Request_Client1`
    FOREIGN KEY (`Client_cpf`)
    REFERENCES `ametista`.`Clients` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Language1`
    FOREIGN KEY (`idLanguage`)
    REFERENCES `ametista`.`Languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Request_Subject1`
    FOREIGN KEY (`idSubject`)
    REFERENCES `ametista`.`Subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`LogStatusUser_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`LogStatusUser_has_Users` (
  `idLogStatus` INT NOT NULL,
  `User_cpf` VARCHAR(100) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idLogStatus`, `User_cpf`),
  INDEX `fk_LogStatusUser_has_User_User1_idx` (`User_cpf` ASC),
  INDEX `fk_LogStatusUser_has_User_LogStatusUser1_idx` (`idLogStatus` ASC),
  CONSTRAINT `fk_LogStatusUser_has_User_LogStatusUser1`
    FOREIGN KEY (`idLogStatus`)
    REFERENCES `ametista`.`LogStatusUsers` (`idLogStatus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LogStatusUser_has_User_User1`
    FOREIGN KEY (`User_cpf`)
    REFERENCES `ametista`.`Users` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`LogStatusRequests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`LogStatusRequests` (
  `id` INT NOT NULL,
  `status` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`LogStatusRequest_has_Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`LogStatusRequest_has_Requests` (
  `idLogStatus` INT NOT NULL,
  `idRequest` CHAR(10) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`idLogStatus`, `idRequest`),
  INDEX `fk_LogStatusRequest_has_Request_Request1_idx` (`idRequest` ASC),
  INDEX `fk_LogStatusRequest_has_Request_LogStatusRequest1_idx` (`idLogStatus` ASC),
  CONSTRAINT `fk_LogStatusRequest_has_Request_LogStatusRequest1`
    FOREIGN KEY (`idLogStatus`)
    REFERENCES `ametista`.`LogStatusRequests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_LogStatusRequest_has_Request_Request1`
    FOREIGN KEY (`idRequest`)
    REFERENCES `ametista`.`Requests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`User_has_Requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`User_has_Requests` (
  `User_cpf` VARCHAR(100) NOT NULL,
  `Request_id` CHAR(10) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`User_cpf`, `Request_id`),
  INDEX `fk_User_has_Request_Request1_idx` (`Request_id` ASC),
  INDEX `fk_User_has_Request_User1_idx` (`User_cpf` ASC),
  CONSTRAINT `fk_User_has_Request_User1`
    FOREIGN KEY (`User_cpf`)
    REFERENCES `ametista`.`Users` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Request_Request1`
    FOREIGN KEY (`Request_id`)
    REFERENCES `ametista`.`Requests` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`User_has_Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`User_has_Languages` (
  `cpfUser` VARCHAR(100) NOT NULL,
  `idLanguage` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`cpfUser`, `idLanguage`),
  INDEX `fk_User_has_Language_Language1_idx` (`idLanguage` ASC),
  INDEX `fk_User_has_Language_User1_idx` (`cpfUser` ASC),
  CONSTRAINT `fk_User_has_Language_User1`
    FOREIGN KEY (`cpfUser`)
    REFERENCES `ametista`.`Users` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_Language_Language1`
    FOREIGN KEY (`idLanguage`)
    REFERENCES `ametista`.`Languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Areas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Areas` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Area_has_Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Area_has_Users` (
  `Area_id` INT NOT NULL,
  `User_cpf` VARCHAR(100) NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`Area_id`, `User_cpf`),
  INDEX `fk_Area_has_User_User1_idx` (`User_cpf` ASC) ,
  INDEX `fk_Area_has_User_Area1_idx` (`Area_id` ASC) ,
  CONSTRAINT `fk_Area_has_User_Area1`
    FOREIGN KEY (`Area_id`)
    REFERENCES `ametista`.`Areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Area_has_User_User1`
    FOREIGN KEY (`User_cpf`)
    REFERENCES `ametista`.`Users` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ametista`.`Area_has_Subjects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ametista`.`Area_has_Subjects` (
  `Area_id` INT NOT NULL,
  `Subject_id` INT NOT NULL,
  `createdAt` TIMESTAMP NULL,
  `updatedAt` TIMESTAMP NULL,
  PRIMARY KEY (`Area_id`, `Subject_id`),
  INDEX `fk_Area_has_Subject_Subject1_idx` (`Subject_id` ASC),
  INDEX `fk_Area_has_Subject_Area1_idx` (`Area_id` ASC),
  CONSTRAINT `fk_Area_has_Subject_Area1`
    FOREIGN KEY (`Area_id`)
    REFERENCES `ametista`.`Areas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Area_has_Subject_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `ametista`.`Subjects` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
